export const recipeSchema = {
    $id: 'recipeSchema',
    type: 'object',
    properties: {
        name: { type: 'string' },
        desc: { type: 'string', default: '' },
        imageUrl: { type: 'string', default: '' },
        courseId: { type: 'number',  },
        cuisineId: { type: 'number' },
        serves: { type: 'number' },
        prepTime: { type: 'number', default: 0 },
        cookingTime: { type: 'number' },
        ingredients: { type: 'array', items: { type: 'string' }, minItems: 1},
        directions: { type: 'array', items: { type: 'string' }, minItems: 1},
        source: { type: 'string', default: '' },
        tags: { type: 'array', items: { type: 'string' }, minItems: 1 },
    },
    example: {
        name: 'Sweet Almond Date Smoothie',
        desc: 'About Sweet Almond Date Smoothie',
        imageUrl: '',
        courseId: 3,
        cuisineId: 6,
        serves: 2,
        prepTime: 0,
        cookingTime: 0,
        ingredients: [
        '1 banana',
        '2 tbsp almond butter',
        '6 dates',
        '1 tsp maple syrup',
        '2 tsp cinnamon',
        '2 cup almond milk, or skim milk',
        ],
        directions: ['Combine all ingredients in blender. Blend until smooth.'],
        source: 'Yuri Elkaim',
        tags: ['smoothie', 'FUF', 'breakfast'],
    },
    additionalProperties: false
} as const
