import { User } from './types'

export const USERS: User[] = [
  {
    id: 1,
    username: 'jarebnorbury',
    firstName: 'Jareb',
    lastName: 'Norbury',
    email: 'jnorbury0@ftc.gov',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    id: 2,
    username: 'derbyreimers',
    firstName: 'Derby',
    lastName: 'Reimers',
    email: 'dreimers1@godaddy.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    id: 3,
    username: 'latisha_rocks',
    firstName: 'Latisha',
    lastName: 'Mercik',
    email: 'lmercik2@jugem.jp',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/61100/pexels-photo-61100.jpeg',
  },
  {
    id: 4,
    username: 'cirsto',
    firstName: 'Cirstoforo',
    lastName: 'Drejer',
    email: 'cdrejer3@de.vu',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/459947/pexels-photo-459947.jpeg',
  },
  {
    id: 5,
    username: 'killough',
    firstName: 'Paola',
    lastName: 'Killough',
    email: 'pkillough4@hubpages.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/449734/pexels-photo-449734.jpeg',
  },
  {
    id: 6,
    username: 'shirley',
    firstName: 'Gaynor',
    lastName: 'Shirley',
    email: 'gshirley5@amazonaws.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg',
  },
  {
    id: 7,
    username: 'harriecollip',
    firstName: 'Harrie',
    lastName: 'Collip',
    email: 'hcollip6@cam.ac.uk',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg',
  },
  {
    id: 8,
    username: 'filbertetrue',
    firstName: 'Filberte',
    lastName: 'Truelock',
    email: 'ftruelock7@angelfire.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/769772/pexels-photo-769772.jpeg',
  },
  {
    id: 9,
    username: 'linetteone',
    firstName: 'Linette',
    lastName: 'Paniman',
    email: 'lpaniman8@sohu.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg',
  },
  {
    id: 10,
    username: 'ailsunbeardy',
    firstName: 'Ailsun',
    lastName: 'Beardshall',
    email: 'abeardshall9@about.me',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/38554/girl-people-landscape-sun-38554.jpeg',
  },
]
