import { User } from './types'

export const USERS: User[] = [
  {
    id: 'oyJrpbMBQU61YDytnSk6W',
    username: 'jarebnorbury',
    firstName: 'Jareb',
    lastName: 'Norbury',
    email: 'jnorbury0@ftc.gov',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    id: 'qCfWu9p_drAA-MpsIDZU4',
    username: 'derbyreimers',
    firstName: 'Derby',
    lastName: 'Reimers',
    email: 'dreimers1@godaddy.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    id: 'q1a6Absl5Emmb4qqzkGCc',
    username: 'latisha_rocks',
    firstName: 'Latisha',
    lastName: 'Mercik',
    email: 'lmercik2@jugem.jp',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/61100/pexels-photo-61100.jpeg',
  },
  {
    id: 'BIQ6nRp6U-IaONb8WbN0u',
    username: 'cirsto',
    firstName: 'Cirstoforo',
    lastName: 'Drejer',
    email: 'cdrejer3@de.vu',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/459947/pexels-photo-459947.jpeg',
  },
  {
    id: 'aeKXGUpLF0SmrqvwL-grT',
    username: 'killough',
    firstName: 'Paola',
    lastName: 'Killough',
    email: 'pkillough4@hubpages.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/449734/pexels-photo-449734.jpeg',
  },
  {
    id: 'f5fDQz6dcIw8VhjpncPWO',
    username: 'shirley',
    firstName: 'Gaynor',
    lastName: 'Shirley',
    email: 'gshirley5@amazonaws.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg',
  },
  {
    id: 'AwGc4M1vYGc6c53k7aiiD',
    username: 'harriecollip',
    firstName: 'Harrie',
    lastName: 'Collip',
    email: 'hcollip6@cam.ac.uk',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg',
  },
  {
    id: 'N6O-AkU0OkPYZc9kzAGDG',
    username: 'filbertetrue',
    firstName: 'Filberte',
    lastName: 'Truelock',
    email: 'ftruelock7@angelfire.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/769772/pexels-photo-769772.jpeg',
  },
  {
    id: 'G68DFtAmiYz0h3CMc2VSh',
    username: 'linetteone',
    firstName: 'Linette',
    lastName: 'Paniman',
    email: 'lpaniman8@sohu.com',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg',
  },
  {
    id: 'l_xq1revWbsbBQyiNd2Xa',
    username: 'ailsunbeardy',
    firstName: 'Ailsun',
    lastName: 'Beardshall',
    email: 'abeardshall9@about.me',
    password: 'Pa33w0rd!',
    avatar: 'https://images.pexels.com/photos/38554/girl-people-landscape-sun-38554.jpeg',
  },
]
